### ISSUE TITLE
Grafana and Prometheus metrics 

### ISSUE THREAD

**Issue by AtulP123** [hiveco/conntrack_exporter#10]
Hello, 

I could not find any list of the metrics that I can use in the Prometheus expression editor. Could someone please share these ? 
Also, could someone also a share the json of the "Open Connections" dashboard whose screenshot is seen in https://github.com/hiveco/conntrack_exporter 

Thanks

**Comment by dbendelman** [comment]
Hi @AtulP123, sorry I didn’t get notifications from this repo and hadn’t stumbled into your issue until now.

If this is still relevant, please take a look [here](https://github.com/hiveco/conntrack_exporter/blob/master/src/main.cc#L133) for the metric names.

I unfortunately don’t have access to the dashboard JSON anymore but it should be easy enough to recreate in Grafana once you know the above metric names.
