### ISSUE TITLE
Grafana Dashboard file

### ISSUE THREAD

**Issue by singhjoga** [hiveco/conntrack_exporter#16]
Hi,
Can somebody provide the Grafana dashboard json file? I could not find it in the source repository.

Thanks in advance.

Regards,

Joga Singh

**Comment by dbendelman** [comment]
@singhjoga if this is still relevant, please take a look [here](https://github.com/hiveco/conntrack_exporter/blob/23a26c8eacfeb59d3ab6d00b384b4f06166345fe/src/main.cc#L138-L155) for the metric names.

I unfortunately don’t have access to the dashboard JSON anymore but it should be easy enough to recreate in Grafana once you know the above metric names.
