### ISSUE TITLE
Add support to run without `--net=host`

### ISSUE THREAD

**Issue by marcosnils** [hiveco/conntrack_exporter#4]
I'm not sure about the specifics but I'd like to track only the connections inside a container and not of the host network namespace. Seems like if you conntrack_exporter inside a network namespace even with NET_ADMIN it won't capture any connections.

Ideas?

**Comment by dbendelman** [comment]
That's an interesting use case. It's not currently supported, and unfortunately I don't have the bandwidth atm to investigate how to adapt the code to work this way.

I can definitely see how this could be useful functionality, so if you get this to work, a PR would be very appreciated.

**Comment by marcosnils** [comment]
I can definitely give it a try and invest some time investigating. Any ideas / clues to where start looking before jumping into the code / debugging?

**Comment by dbendelman** [comment]
I'd start by copying the conntrack_exporter binary into your target container (don't forget to also install libconntrack etc) and seeing if it's publishing the right metrics. Might just be that easy :wink: 

I did a quick test and this looks promising:

```
$ docker run --rm -it --cap-add=NET_ADMIN alpine sh
/ # apk add --update conntrack-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/7) Installing libmnl (1.0.4-r0)
(2/7) Installing libnfnetlink (1.0.1-r1)
(3/7) Installing libnetfilter_conntrack (1.0.6-r0)
(4/7) Installing libnetfilter_cthelper (1.0.0-r0)
(5/7) Installing libnetfilter_cttimeout (1.0.0-r0)
(6/7) Installing libnetfilter_queue (1.0.3-r0)
(7/7) Installing conntrack-tools (1.4.4-r0)
Executing busybox-1.30.1-r2.trigger
OK: 6 MiB in 21 packages
/ # conntrack -L
udp      17 175 src=172.17.0.2 dst=8.8.4.4 sport=36944 dport=53 src=8.8.4.4 dst=172.17.0.2 sport=53 dport=36944 [ASSURED] mark=0 use=1
tcp      6 115 TIME_WAIT src=172.17.0.2 dst=151.121.0.249 sport=42606 dport=80 src=151.121.0.249 dst=172.17.0.2 sport=80 dport=42606 [ASSURED] mark=0 use=1
udp      17 175 src=172.17.0.2 dst=8.8.8.8 sport=36944 dport=53 src=8.8.8.8 dst=172.17.0.2 sport=53 dport=36944 [ASSURED] mark=0 use=1
conntrack v1.4.4 (conntrack-tools): 3 flow entries have been shown.
```

When running that command on my host I get a lot more than 3 entries. `conntrack_exporter` hooks into the same place as `conntrack` so it should likewise show only container connections.

**Comment by marcosnils** [comment]
Nice, so it works in practice. It's just a matter of checking the code to see what's missing to get that info. I'll check it out and hopefully send a PR soon :)

**Comment by marcosnils** [comment]
hey @dbendelman just tried the same thing on my environment and seems like `conntrack` doesn't show anything :(. I think I've read somewhere that this could be introduced in recent kernel versions?

**Comment by dbendelman** [comment]
Just upgraded my Ubuntu 16.04 system to the latest kernel and retried the test in my last comment, still works.

```
/ # uname -r
4.4.0-159-generic
```

@marcosnils what kernel are you running?

**Comment by marcosnils** [comment]
oh! I thought I pasted my output. I'm testing on: `marcos:home/marcos (⎈ |sfo1)$ uname -r
4.15.0-1045-oem`

Btw, I also tried in 4.4 and it works there as well so this reinforces me theory that it should be some sort of kernel changes.
