### ISSUE TITLE
ERROR: regex_error

### ISSUE THREAD

**Issue by sanindd** [hiveco/conntrack_exporter#7]
Hi, I have compiled an exporter for centos7 but I get an error on startup.
[root@cent7 conntrack_exporter-0.3]# ./conntrack_exporter
conntrack_exporter v0.3
ERROR: regex_error
What could be the problem?

Thanks!

**Comment by dbendelman** [comment]
Hi @sanindd, sorry I didn’t get notifications from this repo and hadn’t stumbled into your issue until now.

If this is still relevant, I’m not sure what could cause that error. I’m not working with this exporter atm but would be happy to merge trivial fixes to help the community.
