### ISSUE TITLE
Change metrics path

### ISSUE THREAD

**Issue by crockk** [hiveco/conntrack_exporter#8]
Hi there, would it be possible to implement an additional command line option to change the metrics path from `/metrics` to something else like `/conntrack/metrics` for example? I need to be able to do this due to some nuances working with Cloudflare Argo Tunnels.

**Comment by il-Putzki** [comment]
Try to edit "/metrics" in the main.cc and build an app

**Comment by il-Putzki** [comment]
> Hi there, would it be possible to implement an additional command line option to change the metrics path from `/metrics` to something else like `/conntrack/metrics` for example? I need to be able to do this due to some nuances working with Cloudflare Argo Tunnels.

Try to edit "/metrics" in the main.cc and build an app

**Comment by dbendelman** [comment]
Hi @crockk, sorry I didn’t get notifications from this repo and hadn’t stumbled into your issue until now.

I’d be happy to merge a PR for such a feature if anyone wants to take a crack at it.
