### ISSUE TITLE
Exporter not showing all open connections

### ISSUE THREAD

**Issue by crockk** [hiveco/conntrack_exporter#9]
Hello,

I noticed the metrics are not showing all of the currently open connections on my server. Here is what I get when I `grep` for listening TCP connections on my server:
![image](https://user-images.githubusercontent.com/58015900/115309712-7ee71c00-a121-11eb-8440-595f48cfedeb.png)

Vs what I see in the metrics page:
![image](https://user-images.githubusercontent.com/58015900/115309783-98886380-a121-11eb-975d-455166064f74.png)

1/2 of the connections are not listed.

**Comment by dbendelman** [comment]
@crockk please read [this](https://github.com/hiveco/conntrack_exporter#i-know-some-open-connections-were-closed-why-is-conntrack_closed_connections-not-reporting-them). There are some suggestions mentioned there for what you can do.
